### ISSUE TITLE
Revenant Dogma (PCSE01322) Savefile issue

### ISSUE THREAD

**Issue by TheUnforgiven71** [SKGleba/0syscall6#10]
Hi, I've purchased the physical copy of Revenant Dogma from LimitedRunGames (PCSE01322).
I'm running 3.68 h-encore. I installed 0syscall6 in order to be able to boot the game (it requires 3.69). 
When I launch the game, I get the following error : "New Saved Data - The file is corrupt."
I've tried to delete the savefile using Vitashell or directly in-game, reinstall the game.
Using rePatch didn't fix the issue.

I bought another game from LimitedRunGames that requires 3.69, and the second game is working well.

What can I do to fix the error?

Thanks !

**Comment by SKGleba** [comment]
Use ref00d ( https://github.com/dots-tb/reF00D )

**Comment by TheUnforgiven71** [comment]
Hi, I did, here are the things I've tried so far : https://www.reddit.com/r/VitaPiracy/comments/ev8w29/savefile_corrupted/
