### ISSUE TITLE
Error C1-6703-6 while attempting to run some homebrew

### ISSUE THREAD

**Issue by mathieulh** [SKGleba/0syscall6#3]
I am getting the C1-6703-6 error while attempting to run some homebrew, using the renga version of the plugin with 3.73 kprx_auth_sm.

This happens while trying to run PKGj 0.51 for example.

**Comment by SKGleba** [comment]
There's an issue with your setup then, hbs don't care about cMeP. Are you sure that you are HEN-abled?

**Comment by mathieulh** [comment]
> There's an issue with your setup then, hbs don't care about cMeP. Are you sure that you are HEN-abled?

Yes, I am sure I am HEN enabled, this seems to be an issue with the additional kprx_auth self patches you do. The homebrew itself doesn't even run, that's the whole point.

**Comment by SKGleba** [comment]
I tested on like 4 vitas, no problem with homebrews. And as i said, cMeP does NOT care about HB. And i don't do any kprx patches. The issue may be with libs imported by pkgj, idk, not related to 0syscall6.

**Comment by mathieulh** [comment]
All I can tell, is that as soon as I disable the renga and 0syscall6 plugins, the homebrew works again whereas it can't load the eboot.bin at all while those are enabled.
