### ISSUE TITLE
European version of Ar No Surge opening movie has no sound when using the renga version 

### ISSUE THREAD

**Issue by mathieulh** [SKGleba/0syscall6#9]
I am unsure if it's entirely related but the European version of Ar No Surge (PCSB00798) opening movie has no sound when using the renga version with 3.73 kprx_auth_sm, the problem does not occur using either the standalone version of 0syscall6 or ref00d.

**Comment by SKGleba** [comment]
SRAM or PHYCONT mode?

**Comment by SKGleba** [comment]
Also its a renga issue, so please reopen on the renga repo
